---
  
- set_fact: old_hostname="{{ ansible_facts.hostname }}"
  when: new_hostname |length > 0
  
- name: debug old hostname
  debug:
    msg: "old hostname - {{ old_hostname }}"
    verbosity: 1
  when: new_hostname |length > 0

- name: debug new hostnames
  debug:
    msg: "new hostname - {{ new_hostname }}"
    verbosity: 1
  when: new_hostname |length > 0

- name: rename in /etc/hostname
  hostname:
    name: "{{ new_hostname }}"
  when: new_hostname |length > 0

- name: Update /etc/hosts with new hostname
  replace:
    path: /etc/hosts
    regexp: "{{ old_hostname }}"
    replace: "{{ new_hostname }}"
    backup: yes
  when: new_hostname |length > 0

- set_fact: reboot=True
  when: new_hostname |length > 0

- set_fact: reboot=False
  when: new_hostname |length == 0
