--- 
#start standard apps install  
  
- hosts: localhost
  become: yes
  roles:
    - role: prompt_parameters/hostname
    - role: prompt_parameters/build_type
    - { role: docker, when: "(build_type | select('regex','^docker$') | list | length > 0)" }
    - role: hostname
    - role: cleanup





