---
- hosts: localhost
  become: yes
  roles:
    - role: reboot_and_rerun
      when: os in [ "alma", "debianAz", "ubuntu" ]
    - role: flag_start
    - { role: docker, when: build == "docker" }
    - { role: podman, when: build == "podman" }
    - role: notify_done
