---
- hosts: localhost
  become: yes
  roles:
    - { role: reboot_and_rerun, when: os == "ubuntu" }
    - role: flag_start
    - { role: docker, when: build == "docker" }
    - role: reboot
      when: os in ["alma", "debianAz"] 

