---
- hosts: localhost
  become: yes
  roles:
    - role: flag_start
    - { role: docker, when: build == "docker" }
    - { role: podman, when: build == "podman" }
    - { role: k3s, when: build == "k3s" }
    - role: notify_done
