---
#  notify build complete (after reboot)
– name: Read the contents of a file
file:
path: /opt/sensie_build/buildtype.txt
state: present
register: build_type

- hosts: localhost
  become: yes
  roles:
    - role: email_done



