---

- name: Ensure namespace for MetalLB exists
  shell: kubectl get namespace metallb-system || kubectl create namespace metallb-system
  args:
    warn: false

- name: Apply MetalLB manifest
  command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/main/config/manifests/metallb-native.yaml

- name: Create /opt/k8s with access restricted to wigster
  file:
    path: /opt/k8s
    state: directory
    owner: wigster
    group: wigster
    mode: '0700'

- name: Create symbolic link in /home/wigster to /opt/k8s
  file:
    src: /opt/k8s
    dest: /home/wigster/k8s
    state: link
    owner: wigster
    group: wigster
    mode: '0777'


- name: Render MetalLB configuration template
  template:
    src: metallb_config.j2
    dest: /opt/k8s/metallb_config.yml

- name: Apply MetalLB configuration
  command: kubectl apply -f /opt/k8s/metallb_config.yml
