---
    
- name: Notify ansible finished
  mail:
   host: mta.oc.baltsch.com
   port: 465 
   secure: always
   to: fchorley@gmail.com
   subject: "sensie build ansible {{ build_type }} done"
   body: 'sensie build ansible done'
