---
- name: Write to serial port
  shell: echo "ansible begin install - podman" > /dev/ttyS0
  when: serial_port_enabled

- name: install Podman
  ansible.builtin.package:
    name: podman
    state: present
