---

- name: prompt to download docker configs
  pause:
    prompt: "\nDownload sensie docker configs?\n\ny - yes (default)\nn - no\n\n"
    echo: yes
  register: download_docker_configs_prompt

- set_fact: download_docker_configs="{% if download_docker_configs_prompt.user_input|upper == 'Y' or download_docker_configs_prompt.user_input|length == 0 %}y{% else %} got n{% endif %}"

#- name: dbg download prompt test
#  debug:
#    msg: "download={{download_docker_configs}}"

- name: create directory for configs
  file:
    path: /etc/sensie_install/docker_configs/tars/old
    state: directory
  when: download_docker_configs=="y"   

- name: create root temp dir, avoid /tmp being too small for downloads
  file:
    path: /docker_configs_tmp
    state: directory
  when: download_docker_configs=="y"  
  
- name: load azure params
  include_vars: ../defaults/azure_params.yml 
  
- name: get list of config tars from azure
  ansible.builtin.uri:
    url: "{{get_tars_list_url}}"
    return_content: yes
  register: configs_list
  when: download_docker_configs=="y" 
  
#- name: dbg configs_list
#  debug:
#    msg: "{{configs_list.content}}"

- set_fact: ary_docker_configs={{ configs_list.content.split(",") }}
  when: download_docker_configs=="y"   

- set_fact: ts="{{now(fmt='%a %d %b %Y %I:%M:%S %p CET')}}"
  when: download_docker_configs=="y"   

- name: download configs
  ansible.builtin.get_url:
    url: "{{download_url_prefix}}{{item}}{{download_url_suffix}}"
    dest: "/etc/sensie_install/docker_configs{{item}}"
    timeout: 600
    tmp_dest: /docker_configs_tmp
    headers:
      x-ms-date: "{{ts}}"
  loop: "{{ configs_list.content.split(',') }}"
  loop_control:
    index_var: idx
    label: "{{idx+1}} of {{ary_docker_configs|length}} - {{item}}"
  when: download_docker_configs=="y"   
  
- name: remove root temp dir
  ansible.builtin.file:
    path: /docker_configs_tmp
    state: absent
  when: download_docker_configs=="y"  


