---

- name: Install vim
  ansible.builtin.package:
    name: vim
    state: present

- name: Install nano
  ansible.builtin.package:
    name: nano
    state: present

 - name: Set build type fact
   ansible.builtin.set_fact: build_type="base_apps"
  