- name: Create /opt/k8s_sensie_configs with access restricted to wigster
  file:
    path: /opt/k8s_sensie_configs
    state: directory
    owner: wigster
    group: wigster
    mode: '0700'

- name: Clone k8s repo
  git:
    repo: "https://github.com/jontywigster/k8s_sensie_configs.git"
    dest: "/opt/k8s_sensie_configs"

- name: Create symbolic link in /home/wigster to /opt/k8s_sensie_configs
  file:
    src: /opt/k8s_sensie_configs
    dest: /home/wigster/k8s_sensie_configs
    state: link
    owner: wigster
    group: wigster
    mode: '0777'