- name: Create /opt/k8s_configs with access restricted to cntnr_usr
  file:
    path: /opt/k8s_configs
    state: directory
    owner: "{{ cntnr_usr }}"
    group: "{{ cntnr_usr }}"
    mode: '0700'

- name: Clone k8s repo
  git:
    repo: "https://github.com/jontywigster/k8s_configs.git"
    dest: "/opt/k8s_configs"
  become: yes
  become_user: "{{ cntnr_usr }}"

- name: Create symbolic link in cntnr_usr home to /opt/k8s_configs
  file:
    src: /opt/k8s_configs
    dest: /home/{{ cntnr_usr }}/k8s_configs
    state: link
    owner: "{{ cntnr_usr }}"
    group: "{{ cntnr_usr }}"
    mode: '0777'