- name: Create /opt/k8s_configs with access restricted to CONTAINER_USER
  file:
    path: /opt/k8s_configs
    state: directory
    owner: "{{ CONTAINER_USER }}"
    group: "{{ CONTAINER_USER }}"
    mode: '0700'

- name: Clone k8s repo
  git:
    repo: "https://github.com/jontywigster/k8s_configs.git"
    dest: "/opt/k8s_configs"
  become: yes
  become_user: "{{ CONTAINER_USER }}"

- name: Create symbolic link in CONTAINER_USER home to /opt/k8s_configs
  file:
    src: /opt/k8s_configs
    dest: /home/{{ CONTAINER_USER }}/k8s_configs
    state: link
    owner: "{{ CONTAINER_USER }}"
    group: "{{ CONTAINER_USER }}"
    mode: '0777'