---

- name: set h-v kvp flag
  shell: printf "sensie_build%0500dbase%02044d" | tr '0' '\0' > /var/lib/hyperv/.kvp_pool_1
  async: 1
  poll: 0
  when: kvp_flag

- name: Write to serial port
  shell: echo "ansible play start" > /dev/ttyS0
  when: serial_flag