---

- name: set h-v kvp flag
  shell: printf "sensie_build%0500ddonee%02044d" | tr '0' '\0' > /var/lib/hyperv/.kvp_pool_1
  async: 1
  poll: 0

- name: set build type fact
  set_fact:
    build_type: "{{ lookup('ansible.builtin.file', '/opt/sensie_build/buildtype.txt') }}"

- name: Notify ansible finished
  community.general.mail:
    host: mta.oc.baltsch.com
    port: 465 
    secure: always
    to: fchorley@gmail.com
    sender: fchorley@gmail.com
    subject: "sensie build playbook {{ build_type }} done"
    body: "sensie build playbook {{ build_type }} done"
