---

- name: set h-v kvp flag
  shell: printf "sensie_build%0500ddone%02044d" | tr '0' '\0' > /var/lib/hyperv/.kvp_pool_1
  async: 1
  poll: 0

- name: set build type fact
  set_fact:
    build_type: "{{ lookup('ansible.builtin.file', 'buildtype.txt') }}"

- name: read build log
  set_fact:
    build_log: "{{ lookup('ansible.builtin.file', './build.log') }}"

- name: notify ansible finished
  community.general.mail:
    host: mta.oc.baltsch.com
    port: 465 
    secure: always
    to: fchorley@gmail.com
    sender: fchorley@gmail.com
    subject: "{{ansible_hostname}}"
    body: |
      sensie {{ build_type }} build done for {{ansible_hostname}}
      
      Build Log:
      {{ build_log }}

- name: remove crontab build done notify'
  ansible.builtin.cron:
    name: "sensie build notify done"
    state: absent