---

- name: Install vim
  ansible.builtin.package:
    name: vim
    state: present

- name: Install nano
  ansible.builtin.package:
    name: nano
    state: present

- name: set build type flag
  copy:
    content: |
      base_apps     
    dest: /opt/sensie_build/buildtype.txt
    force: true
    group: root
    owner: root
    mode: 0644