---

- name: Install geerlingguy's Ansible Galaxy Docker role
  command: "ansible-galaxy install geerlingguy.docker"

- name: install docker (non-photon)
  ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose_plugin: true
    docker_install_compose: false
    docker_users:
     - wigster

- name: Set build type fact
  set_fact: 
    build_type="docker"
