---

- name: set h-v kvp flag
  shell: printf "sensie_build%0500ddock%02044d" | tr '0' '\0' > /var/lib/hyperv/.kvp_pool_1
  async: 1
  poll: 0
  when: kvp_flag_enabled

- name: Write to serial port
  shell: echo "ansible begin install - docker" > /dev/ttyS0
  when: serial_port_enabled

- name: Install geerlingguy's Ansible Galaxy Docker role
  command: "ansible-galaxy install geerlingguy.docker"

- name: install docker (non-photon)
  ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose_plugin: true
    docker_install_compose: false
    CONTAINER_USERs:
     - "{{ lookup('env', 'CONTAINER_USER') }}"

- name: enable docker daemon user ns remap
  copy:
    content: |
      {
      "userns-remap": "default"
      }        
    dest: /etc/docker/daemon.json
    force: false
    group: root
    owner: root
    mode: 0644

- name: Create /opt/docker with access restricted to the specified user
  file:
    path: /opt/docker
    state: directory
    owner: "{{ lookup('env', 'CONTAINER_USER') }}"
    group: "{{ lookup('env', 'CONTAINER_USER') }}"
    mode: '0700'

- name: Create /opt/docker with access restricted to a user from environment variable
  file:
    path: /opt/docker
    state: directory
    owner: "{{ lookup('env', 'CONTAINER_USER') }}"
    group: "{{ lookup('env', 'CONTAINER_USER') }}"
    mode: '0700'


- name: Create symbolic link in CONTAINER_USER home to /opt/docker
  file:
    src: /opt/docker
    dest: "/home/{{ lookup('env', 'CONTAINER_USER') }}/docker"
    state: link
    owner: "{{ lookup('env', 'CONTAINER_USER') }}"
    group: "{{ lookup('env', 'CONTAINER_USER') }}"
    mode: '0777'
