---

- name: set h-v kvp flag
  shell: printf "sensie_build%0500ddock%02044d" | tr '0' '\0' > /var/lib/hyperv/.kvp_pool_1
  async: 1
  poll: 0

- name: Install geerlingguy's Ansible Galaxy Docker role
  command: "ansible-galaxy install geerlingguy.docker"

- name: install docker (non-photon)
  ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose_plugin: true
    docker_install_compose: false
    docker_users:
     - wigster

- name: enable docker daemon user ns remap
  copy:
    content: |
      {
      "userns-remap": "default"
      }        
    dest: /etc/docker/daemon.json
    force: false
    group: root
    owner: root
    mode: 0644
