---

- name: Check if the playbook has already been run
  ansible.builtin.stat:
    path: /opt/sensie_build/post_reboot_flag
  register: playbook_flag

- name: Set a fact if this is the second run
  ansible.builtin.set_fact:
    second_run: true
  when: playbook_flag.stat.exists

- name: Create a flag file to mark the first run
  ansible.builtin.file:
    path: /opt/sensie_build/post_reboot_flag
    state: touch
  when: not playbook_flag.stat.exists

- name: Create a cronjob to run the playbook on boot
  ansible.builtin.cron:
    name: "Run local playbook on boot"
    special_time: reboot
    job: "ansible-playbook /opt/sensie_build/local.yml -e os={{ os }}"
  when: not playbook_flag.stat.exists

- name: Force Reboot the machine
  shell:
    cmd: "sleep 5 && reboot"
  async: 1
  poll: 0
  ignore_errors: true
  when:
    - not playbook_flag.stat.exists