---

- name: Check if the playbook has already been run
  ansible.builtin.stat:
    path: /opt/sensie_build/post_reboot_flag
  register: playbook_flag

- name: set h-v kvp flag
  shell: printf "sensie_build%0500drebo%02044d" | tr '0' '\0' > /var/lib/hyperv/.kvp_pool_1
  async: 1
  poll: 0
  when: kvp_flag_enabled

- name: Write to serial port
  shell: echo "ansible calling reboot" > /dev/ttyS1
  when: serial_port_enabled

- name: Set a fact if this is the second run
  ansible.builtin.set_fact:
    second_run: true
  when: playbook_flag.stat.exists

- name: Create a flag file to mark the first run
  ansible.builtin.file:
    path: /opt/sensie_build/post_reboot_flag
    state: touch
  when: not playbook_flag.stat.exists

- name: Create a cronjob to run the playbook on boot
  ansible.builtin.cron:
    name: "Run local playbook on boot"
    special_time: reboot
    job: "ansible-playbook /opt/sensie_build/local.yml -e os={{ os }} -e build={{ build }}"
  when: not playbook_flag.stat.exists

- name: Force Reboot the machine
  shell:
    cmd: "shutdown -r now"
  async: 1
  poll: 0
  ignore_errors: true
  when:
    - not playbook_flag.stat.exists

- name: Force Reboot the machine
  shell:
    cmd: "shutdown -r now"
  async: 1
  poll: 0
  ignore_errors: true
  when:
    - not playbook_flag.stat.exists

- name: End play after reboot is triggered
  meta: end_play
  when:
    - not playbook_flag.stat.exists

- name: Remove the cronjob after reboot
  ansible.builtin.cron:
    name: "Run local playbook on boot"
    state: absent
  when: playbook_flag.stat.exists
