---

- name: prompt for build type
  pause:
    prompt: "\nSelect build number\n\n1 - bare (default)\n2 - docker\n\n"
    echo: yes
  register: build_type_prompt
  
#set a default  
- set_fact: 
    build_type: [bare]

- set_fact: 
    build_type: [docker,docker-compose]
  when: ( build_type_prompt.user_input == "2" )






