---
# h-v ipv6 over wifi seems intermittent, prefer ipv4 for now
- name: Update gai.conf to prefer IPv4
  lineinfile:
    path: /etc/gai.conf
    regexp: '^#precedence ::ffff:0:0/96'
    line: 'precedence ::ffff:0:0/96  100'
    state: present